### ISSUE TITLE
Manual tasks not executed after restart due to installation changes

### ISSUE THREAD

**Issue by mmosconi1** [eclipse-oomph/oomph#70] opened 2024-03-04 17:49 UTC
If I invoke "Perform Setup Tasks..." and the Manual Tasks to be executed require a restart (e.g. P2 changes), the remaining Manual Tasks are not executed after the restart.

**Comment by merks** [comment] 2024-03-04 17:55
Now that you mention it, I think I ran into that today myself, but with all the multi-tasking I didn't pay so much attention.  Maybe it's related to the new restart behavior of the Platform...

**Comment by mmosconi1** [comment] 2024-03-04 18:46
Btw - "Skip automatic task execution at startup time" in preferences is disabled.
I guess, even if this is enabled, in case of a "Perform Setup Tasks..." manual invocation, it should be ignored if a restart is involved.

**Comment by mmosconi1** [comment] 2024-03-05 14:56
I can reproduce with the [attached setup](https://github.com/eclipse-oomph/oomph/files/14496792/Test70.setup.txt). It contains:

- an Eclipse Ini Task to trigger restart (modified by a user variable)
- a Maven Update Task (set to MANUAL only)
- a Launch Task (set to STARTUP MANUAL with "run every startup"=false)
- a Projects Build Task (set to STARTUP MANUAL)

After initial installation, run "Perform Setup Tasks", go back in the wizard and change value of "foo" and proceed with all Manual Tasks selected.
My results:

- 2022-06 (Oomph also ~2022-06): MANUAL and STARTUP tasks are triggered after restart as expected ✔️ 
- 2022-12 / 2023-03 / 2023-06 / 2024-03: nothing is executed after restart due to changed eclipse.ini ❌ 

Note that the latter all get the following installed:
Oomph Setup	1.31.0.v20240211-0940
Oomph Setup Launching	1.18.0.v20230617-1322

Nothing suspicious in the logs.

**Comment by merks** [comment] 2024-03-06 10:44
I could reproduce this problem, but I get the sense it's reproducible because of how I am testing:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/ea0ae8cd-c82e-40ba-9da8-2b18db9534f3)

It's comparing the URIs of the things to be restarted against the URI of the task in the performer.  

So I wonder if something like that is happening in your case too, i.e., some funky redirections or maybe even your own index.

In any case, I will try to add some logic that will hopefully generally fix such an issue.

**Comment by merks** [comment] 2024-03-06 11:18
@mmosconi1 

I committed a change that I think/hope will fix the problem generally.  A build to produce a nightly update site is running

https://ci.eclipse.org/oomph/job/build/job/master/467/

This takes about an hour to complete (because mac notarization of the installers takes really long).

I must build the final 1.32 release today for contribution to SimRel 2024-03 later today...

Would you be able to test that this actually fixes the problem for you after the build is completed?

https://download.eclipse.org/oomph/updates/nightly/latest/

If there is still a problem, please locate this file and share the contents:
```
<workspace>/.metadata/.plugins/org.eclipse.oomph.setup.ui/restarting
```
Be sure that the installed bundle `org.eclipse.oomph.setup.ui` has today's timestamp for the version qualifier.   

If you don't have time, what's there now will be what's in the final release.

**Comment by merks** [comment] 2024-03-06 15:26
I've started the release build...

**Comment by mmosconi1** [comment] 2024-03-06 16:32
I'm a bit late, but - it works now! 👍 
With local user setup (under Eclipse project catalog) as well as with our company-internal redirected index.
Cool!

**Comment by merks** [comment] 2024-03-06 16:35
That makes me feel good. Thanks for the confirmation.

**Closed by merks** 2024-03-06 16:35 UTC
