### ISSUE TITLE
Problem with Installer Build 329 Version 1.31.0

### ISSUE THREAD

**Issue by subhadip-kundu** [eclipse-oomph/oomph#59] opened 2024-01-11 19:13 UTC
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.31.0+Build+329).

 I understand that without details about the problem and how to reproduce then problem, no one can fix a problem for me.  Therefore I have attached log details and screen captures below:
```
![image](https://github.com/eclipse-oomph/oomph/assets/124190254/12f9461a-4dd1-4c84-887d-d290324093e5)
```

**Comment by merks** [comment] 2024-01-12 08:21
This is duplicate of https://github.com/eclipse-oomph/oomph/issues/60 I assume.

**Closed by merks** 2024-01-12 08:21 UTC
